apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: er1bwf4r1-python
  janus-idp.io/tekton: er1bwf4r1-python
  backstage.io/kubernetes-id: er1bwf4r1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: er1bwf4r1-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
